#!/usr/bin/env python3
"""
Generate optimized motion config for site-wide 3D animations.
Outputs CSS custom properties to src/styles/motion-config.css so the theme
and mascot use consistent, tuned values. Run from website/scripts/.
"""
from pathlib import Path
import json

# Tuned for subtle, cohesive motion across the page (not just hero)
CONFIG = {
    "mascot": {
        "float_duration": "9s",
        "float_offset_y": "6px",
        "glow_duration": "5s",
        "easing": "ease-in-out",
        "scale": "0.22",
        "opacity": "0.85",
    },
    "cards": {
        "perspective": "1200px",
        "tilt_max_deg": "4",
        "tilt_hover_deg_x": "2",
        "tilt_hover_deg_y": "-3",
        "transition_duration": "0.35s",
        "easing": "ease-out",
    },
    "sections": {
        "stagger_step": "0.08s",
        "fade_in_duration": "0.6s",
    },
    "links": {
        "tilt_max_deg": "2",
        "transition_duration": "0.25s",
    },
}


def css_escape(s: str) -> str:
    return s.replace('"', '\\"')


def main():
    repo_root = Path(__file__).resolve().parent.parent
    out_css = repo_root / "src" / "styles" / "motion-config.css"
    out_css.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* Generated by scripts/generate_animation_config.py — edit that script to tune. */",
        ":root {",
    ]
    for section, pairs in CONFIG.items():
        for key, val in pairs.items():
            var_name = f"--motion-{section}-{key}"
            lines.append(f"  {var_name}: {css_escape(str(val))};")
    lines.append("}")

    out_css.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_css}")

    out_json = repo_root / "src" / "data" / "animations.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(CONFIG, indent=2), encoding="utf-8")
    print(f"Wrote {out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
